### ISSUE TITLE
Unexpected Behaviour with settings used

### ISSUE THREAD

**Issue by immanuel-odisho** [lix229/UnityRuntimeImport#30] opened 2021-03-04 20:42 UTC
Repro:
1. Use the settings included in the photo below
2. Click Play

Observations:
Unexpected random behaviour
Expectation:
Controlled or reset to default if input is out of range.
![Capture](https://user-images.githubusercontent.com/35702189/110027655-42419b80-7d00-11eb-99f4-c67f0bbf7040.PNG)

**Comment by lix229** [comment] 2021-03-23 19:58
This is kind of the expected behavior, as you are rotating the object around the point with cordinate [121,1212,1212], that would be way out of your field of view so indeed nothing can be seen.

Duplicate of #1

**Closed as completed by lix229** 2021-03-23 19:58 UTC
Labels: duplicate
