### ISSUE TITLE
HCI: Formatting Issue on web app

### ISSUE THREAD

**Issue by IndiW** [lix229/UnityRuntimeImport#66] opened 2021-03-08 16:01 UTC
# Severity
Low

# Environment
Windows 10 Pro, Chrome

# Steps to recreate
Opened the web app in Chrome

# Expected behavior
The navigation buttons and button slider should be formatted as seen in the testing procedure doc

# Actual Behavior
The navigation bar seems to be lacking its CSS and the button slider is overlapping the other texts

![image](https://user-images.githubusercontent.com/45280177/110346370-787f6380-7ffd-11eb-91fe-3a4b668f46e9.png)

**Comment by lix229** [comment] 2021-03-23 21:45
Duplicate of #1

**Closed as completed by lix229** 2021-03-23 21:45 UTC
Labels: duplicate, UI Fix
