### ISSUE TITLE
Runtime Import Module - large scaling values make object disappear with no console errors

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#65] opened 2021-03-08 03:34 UTC
### Description:
Unfortunately, large errors for the scaling of the objects in the sampleAnim.txt do not even throw unity errors in the unity console-thus they must be handled application-side to limit numbers so large that they make the object disappear.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the unity sampleProject scene

Paste this into SampleAnim.txt:

Default,1,NA
1,Obj,Default,0,0,0,0,0,0,0,0,0,1,1,1
1,Default,1000,0,0,0,0,180,180,180,9999999999993,3,3
1,Default,2000,0,0,0,0,360,360,360,5,5,5
1,Default,3000,0,0,0,0,540,540,540,3,3,3
1,Default,4000,0,0,0,0,720,720,720,1,1,1

Play the scene

### Actual Result:
The object disappears between the initialization of the animation and the first keyframe. ![image](https://user-images.githubusercontent.com/29803319/110271000-21de3f00-7f95-11eb-9a69-ccbbd7d92c71.png)
Slightly smaller x scaling (i.e. 9999999) makes the object visible as a long skinny pole, otherwise, for some reason the whole object disappears if the pole becomes too long.
![image](https://user-images.githubusercontent.com/29803319/110271043-391d2c80-7f95-11eb-9dd7-f131e677fcec.png)

### Expected:
A gracefully handled error limiting the maximum size before the object disappears
### Severity: Medium

**Comment by lix229** [comment] 2021-03-23 21:44
Duplicate of #41

**Closed as completed by lix229** 2021-03-23 21:44 UTC
Labels: duplicate
