### ISSUE TITLE
Adding negative keyframe breaks keyframe slider.

### ISSUE THREAD

**Issue by IndiW** [lix229/UnityRuntimeImport#71] opened 2021-03-08 16:32 UTC
# Severity
Medium

# Environment
Windows 10 Pro, Firefox

# Steps to recreate
Open web app. Add -20 to frametime. Add 20, 20, 20 to scale values. Press play.

# Expected behavior
A negative frametime will not be accepted.

# Actual Behavior
The negative value is accepted. Causes visual issues with the background animation and causes the keyframe slider to remain stuck to the far left. Cannot interact with the slider anymore.

![image](https://user-images.githubusercontent.com/45280177/110350430-b4b4c300-8001-11eb-9622-1ca174c97cc4.png)

**Comment by lix229** [comment] 2021-03-23 21:52
Duplicate of #31

**Closed as completed by lix229** 2021-03-23 21:52 UTC
