### ISSUE TITLE
Importing Image caused infinite play

### ISSUE THREAD

**Issue by IndiW** [lix229/UnityRuntimeImport#68] opened 2021-03-08 16:08 UTC
# Severity
High

# Environment
Windows 10 Pro, Chrome

# Steps to recreate
Open web app. Choose image to upload. Click export. 

# Expected behavior
The program would identify an invalid import and would notify the user while discarding the file.

# Actual Behavior
The frametime sets itself to NaN. When play is clicked, the frametime perpetually runs.

![image](https://user-images.githubusercontent.com/45280177/110347167-59350600-7ffe-11eb-8b8a-a4af5b3f395a.png)

**Comment by lix229** [comment] 2021-03-23 21:47
Duplicate of #42

**Closed as completed by lix229** 2021-03-23 21:47 UTC
Labels: duplicate
