### ISSUE TITLE
Cube disappears on web app

### ISSUE THREAD

**Issue by IndiW** [lix229/UnityRuntimeImport#70] opened 2021-03-08 16:28 UTC
# Severity
Medium

# Environment
Windows 10 Pro, Firefox

# Steps to recreate
Start web app. Set the rotation of a keyframe to -2300000000000000000000000000000000000000000000000 for the degree. 

# Expected behavior
Either an invalid input prompt will be displayed or the user will not be able to set this value in the input box.

# Actual Behavior
When inputting -2300000000000000000000000000000000000000000000000 for the degree, the cube disappears

![image](https://user-images.githubusercontent.com/45280177/110350010-4b34b480-8001-11eb-84bd-9ec4e83b461e.png)

**Comment by lix229** [comment] 2021-03-23 21:51
Duplicate of #41

**Closed as completed by lix229** 2021-03-23 21:51 UTC
Labels: duplicate
