### ISSUE TITLE
Animation editor - animation plays with no inputs from user

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#58] opened 2021-03-08 02:07 UTC
### Description:
An animation plays when the user presses play with no other inputs, signifying that the cube is not properly zeroed in it's initial state. Also, the scroll bar current position pointer either does not move or moves to the halfway point when pressing play when no keyframe is added by the user.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
Press play without adding a keyframe

### Actual Result:
This is halfway through the animation when play is pressed and nothing was added by the user (the scrollbar does not move at all from this position:
![image](https://user-images.githubusercontent.com/29803319/110265262-2ef53100-7f89-11eb-9fe1-a455a89f3c61.png)

### Expected Result:
The cube should be zeroed i.e. the start state should match the end state when the inputs are all blank, or if this is intentional, then it should be somehow conveyed to the user that the cube is not initially zeroed. Also, the start button should potentially not be able to be pressed without a keyframe inserted by the user.

**Comment by lix229** [comment] 2021-03-23 21:02
This is the default behavior if no animation data was loaded.

Probably will be changed.

Duplicate of #11

**Closed as completed by lix229** 2021-03-23 21:02 UTC
Labels: duplicate
