### ISSUE TITLE
Animation Editor - z scaling above 100 introduces graphical artifacts

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#62] opened 2021-03-08 02:59 UTC
### Description:
Whenever a large enough z scaling is added, graphical artifacts appear on the entire screen. The larger the absolute value of the z-scaling (and the faster it occurs), the more graphical artifacts appear as the animation goes on.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
Put in any frametime, and for the settings, and input any absolute z scaling above 100 (1 and 1 for x and y respectively)
add keyframe
play the animation

### Actual Result:
![image](https://user-images.githubusercontent.com/29803319/110268667-10deff00-7f90-11eb-8a27-8877a7ed62bb.png)
And it consistently gets progressively worse, even affecting the search bar of my browser:
![image](https://user-images.githubusercontent.com/29803319/110268750-3966f900-7f90-11eb-8145-07fe4928f138.png)

### Expected Result:
No graphical artifacts

**Comment by lix229** [comment] 2021-03-23 21:10
Duplicate of #61 

This is not really artifacts just you stretching the object in z axis to an extreme extent....

**Closed as completed by lix229** 2021-03-23 21:10 UTC
Labels: duplicate
