### ISSUE TITLE
Animation editor - input boxes for all settings cut off numbers after 4 digits

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#57] opened 2021-03-08 02:02 UTC
### Description:
Whenever no transformations are added but a keyframe with a correct frametime is added, the user still gets a "keyframe added" confirmation dialogue before the error pops up.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
input any number in the left settings panel above 9999

### Actual Result:
The frametime with the scrollbar all the way at the end should display 10000 but it seems like it is at 1000 (this goes for all the input settings boxes)
![image](https://user-images.githubusercontent.com/29803319/110264817-26502b00-7f88-11eb-9b9b-542657640186.png)

### Expected Result:
The box should somehow let the user know that the number is bigger than it appears to be- scaling input boxes, a scrollbar, an ellipsis, etc

**Comment by lix229** [comment] 2021-03-23 20:57
Duplicate of #56

**Closed as completed by lix229** 2021-03-23 20:57 UTC
