### ISSUE TITLE
Instant animation button partially covered by scrubber

### ISSUE THREAD

**Issue by Gregory-Kitching** [lix229/UnityRuntimeImport#37] opened 2021-03-04 21:00 UTC
The "Instant Animation" checkbox is partially covered by the scrubber bar's hitbox, clicking too high on the checkbox moves the scrubber instead.

![Screenshot (44)](https://user-images.githubusercontent.com/79662360/110028534-605bcb80-7d01-11eb-8533-f254de62ab2f.png)

![Screenshot (45)](https://user-images.githubusercontent.com/79662360/110028548-6356bc00-7d01-11eb-9bac-1c64e6da2a02.png)

I couldn't get Windows to record the cursor in the screenshots, but it was an arrow in the first screenshot, but changed to a pointing hand in the second screenshot after I tried to click the checkbox. It is hovering over the top half of the "Instant Animation" checkbox in both images.

**Comment by lix229** [comment] 2021-03-23 20:22
Duplicate of #5

**Closed as completed by lix229** 2021-03-23 20:22 UTC
