### ISSUE TITLE
Animation Editor -  Instant Animation not working

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#15] opened 2021-02-26 18:43 UTC
Using firefox.

I assume Instant Animation is supposed to work the same as in the editor, but the cube animation is still smoothed while checked in editor.

**Comment by lix229** [comment] 2021-03-23 18:37
I cannot reproduce this issue with Firefox 87.0 (64-bit) on macOS.

Would you please provide a more detailed recreation step and your environment, with expected and actual behavior?

Note that `instant animation` only means the transision from previous frame to the frame with checkbox checked will be instant. Thus if only 2 frames exists, the difference might be unnoticable due to playback looping instantly resets the animations.

**Closed as completed by lix229** 2021-03-23 18:37 UTC
