### ISSUE TITLE
Animation Editor - some settings cause infinite unstoppable animation loop

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#52] opened 2021-03-08 00:02 UTC
### Description:
An infinite loop that holds a high risk for those with epilepsy occurs, with short frametime values + any values of scale above ~10 on any of the x, y, z axes.

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
put in the settings as:

Rotation:  x-12, y-21, z-32, deg-321
Scale: x-31, y-32, z-22
Translate: x:-2, y-3, z-1

And set the frametime to 200ms and press play

### Actual Result:
a flashing infinite loop that would very easily cause epileptic shock occurs with no way for the user to pause the animation
![image](https://user-images.githubusercontent.com/29803319/110259722-34498000-7f77-11eb-85fa-6fcc6d87db5b.png)
### Expected Result:
Animation should be stoppable either by clicking play, clicking and holding the slider, or at the very least with a certain keyboard shortcut.

**Comment by lix229** [comment] 2021-03-23 20:53
Duplicate of #1

**Closed as completed by lix229** 2021-03-23 20:53 UTC
