### ISSUE TITLE
Animation Editor - No limitation on values for Frametime, Rotation, Scale, Translate

### ISSUE THREAD

**Issue by Rubinstd** [lix229/UnityRuntimeImport#34] opened 2021-03-04 20:51 UTC
### Severity
Medium

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the animation editor
1. Submit the value 3 ms for Framtime
2. Make every other input a value of "a"
3. Add the keyframe.
4. 
### Expected:
There should be an error as "a" is not a valid coordinate.

### Actual:
The frame is successfully added and makes the cube spin wildly.

### Notes:
Other issues have talked about the ability to add negative values to the frametime. This issue specifically talks about how there is no limits on ANY input box, and furthermore, that invalid values can actually result in valid changes to an animation (rather than having a negative keyframe that never shows up).

**Comment by lix229** [comment] 2021-03-23 20:04
Duplicate of #31

**Closed as completed by lix229** 2021-03-23 20:04 UTC
Labels: bug, duplicate
