### ISSUE TITLE
"Import" does not work while testing the Animation Editor

### ISSUE THREAD

**Issue by lim147** [lix229/UnityRuntimeImport#2] opened 2021-02-25 19:07 UTC
After I click on the "Import" tab, I was expecting a folder navigation window props out where I can select the local animation txt file. However nothing happens.

**Comment by zhouh46** [comment] 2021-02-26 01:26
Thanks for the feedback! 
I've merged the code with those two functions into the repo, which was caused by conflicts before, and they should be fine now!

**Comment by lix229** [comment] 2021-03-23 18:41
This should have been fixed.

**Closed as completed by lix229** 2021-03-23 18:41 UTC
Labels: bug
