### ISSUE TITLE
Scaling Overlaps Buttons

### ISSUE THREAD

**Issue by IndiW** [lix229/UnityRuntimeImport#67] opened 2021-03-08 16:05 UTC
# Severity
High

# Environment
Windows 10 Pro, Chrome

# Steps to recreate
Start web app and set scaling x = 200, y = 200, z = -2

# Expected behavior
Scaled cube should not interfere with the user input fields

# Actual Behavior
The image fills the entire screen. Makes it difficult to press pause without good timing.

![image](https://user-images.githubusercontent.com/45280177/110346824-f3e11500-7ffd-11eb-876e-911a56393ed5.png)

**Comment by lix229** [comment] 2021-03-23 21:46
Duplicate of #1

**Closed as completed by lix229** 2021-03-23 21:46 UTC
Labels: duplicate
