### ISSUE TITLE
Animation Editor - Scale Values Oddly Populate By Moving Scrubber Right and Back

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#47] opened 2021-03-07 19:01 UTC
### Description:
When loading up the webpage for the first time, the scale values are empty; however after moving the scrubber to the right and back, they are suddenly populated with the value of `1`.

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open the Animation Editor 
2. Move scrubber to the right
3. Move scrubber back to the beginning

### Actual Result:

Initial:

![image](https://user-images.githubusercontent.com/25377291/110251181-59c19400-7f4d-11eb-8015-24609d25fc57.png)

After moving scrubber to the right and back:

![image](https://user-images.githubusercontent.com/25377291/110251188-6219cf00-7f4d-11eb-9acb-8660767976fb.png)

### Expected Result:

Scale values should not magically populate due to moving the scrubber. I would expect them to initally display '1', if that is their initial value.

### Severity: Medium

**Comment by lix229** [comment] 2021-03-23 20:41
Duplicate of #46

**Closed as completed by lix229** 2021-03-23 20:41 UTC
